/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_funnydwarf_iot_nml_Pin */

#ifndef _Included_ru_funnydwarf_iot_nml_Pin
#define _Included_ru_funnydwarf_iot_nml_Pin
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     ru_funnydwarf_iot_nml_Pin
 * Method:    setMode
 * Signature: (ILru/funnydwarf/iot/nml/Pin/PinMode;)V
 */
JNIEXPORT void JNICALL Java_ru_funnydwarf_iot_nml_Pin_setMode
        (JNIEnv *env, jclass jc, jint pin, jint modeCode);

#ifdef __cplusplus
}
#endif
#endif
