/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_funnydwarf_iot_nml_PinDigitalWriter */

#ifndef _Included_ru_funnydwarf_iot_nml_PinDigitalWriter
#define _Included_ru_funnydwarf_iot_nml_PinDigitalWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_funnydwarf_iot_nml_PinDigitalWriter
 * Method:    digitalWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ru_funnydwarf_iot_nml_PinDigitalWriter_digitalWrite
  (JNIEnv *env, jclass jc, jint portNumber);

#ifdef __cplusplus
}
#endif
#endif
