/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_funnydwarf_iot_nml_modules_onewire_OneWire */

#ifndef _Included_ru_funnydwarf_iot_nml_modules_onewire_OneWire
#define _Included_ru_funnydwarf_iot_nml_modules_onewire_OneWire
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Поиск следующего подключенного устройства
 * Class:     ru_funnydwarf_iot_nml_modules_onewire_OneWire
 * Method:    searchNextAddress
 * Signature: (IJI)[J
 */
JNIEXPORT jlongArray JNICALL Java_ru_funnydwarf_iot_nml_modules_onewire_OneWire_searchNextAddress
        (JNIEnv *env, jclass jc, jint pin, jlong lastAddress, jlong lastDiscrepancy);


/*
 * Class:     ru_funnydwarf_iot_nml_modules_onewire_OneWire
 * Method:    readRom
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ru_funnydwarf_iot_nml_modules_onewire_OneWire_readRom
        (JNIEnv *env, jclass jc, jint pin);

#ifdef __cplusplus
}
#endif
#endif
