/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_funnydwarf_iot_nml_modules_onewire_DS18B20OneWireUnit */

#ifndef _Included_ru_funnydwarf_iot_nml_modules_onewire_DS18B20OneWireUnit
#define _Included_ru_funnydwarf_iot_nml_modules_onewire_DS18B20OneWireUnit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_funnydwarf_iot_nml_modules_onewire_DS18B20OneWireUnit
 * Method:    takeMeasurements
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_funnydwarf_iot_nml_modules_onewire_DS18B20OneWireUnit_takeMeasurements
  (JNIEnv *env, jclass jc, jint pin);

/*
 * Class:     ru_funnydwarf_iot_nml_modules_onewire_DS18B20OneWireUnit
 * Method:    getTemperatureFromUnit
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_ru_funnydwarf_iot_nml_modules_onewire_DS18B20OneWireUnit_getTemperatureFromUnit
  (JNIEnv *env, jclass jc, jint pin);

#ifdef __cplusplus
}
#endif
#endif
