/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_funnydwarf_iot_nml_modules_sensor_reader_NativeReader */

#ifndef _Included_ru_funnydwarf_iot_nml_modules_sensor_reader_NativeReader
#define _Included_ru_funnydwarf_iot_nml_modules_sensor_reader_NativeReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_funnydwarf_iot_nml_modules_sensor_reader_NativeReader
 * Method:    digitalRead
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_ru_funnydwarf_iot_nml_modules_sensor_reader_NativeReader_digitalRead
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
