/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_funnydwarf_iot_nml_modules_receiver_writer_NativeWriter */

#ifndef _Included_ru_funnydwarf_iot_nml_modules_receiver_writer_NativeWriter
#define _Included_ru_funnydwarf_iot_nml_modules_receiver_writer_NativeWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_funnydwarf_iot_nml_modules_receiver_writer_NativeWriter
 * Method:    digitalWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ru_funnydwarf_iot_nml_modules_receiver_writer_NativeWriter_digitalWrite
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
