/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_funnydwarf_iot_nml_modules_OutputModule */

#ifndef _Included_ru_funnydwarf_iot_nml_modules_OutputModule
#define _Included_ru_funnydwarf_iot_nml_modules_OutputModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_funnydwarf_iot_nml_modules_OutputModule
 * Method:    digitalWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ru_funnydwarf_iot_nml_modules_OutputModule_digitalWrite
        (JNIEnv *env, jclass js, jint pin, jint value);

#ifdef __cplusplus
}
#endif
#endif
