/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_funnydwarf_iot_nml_JNILibrary */

#ifndef _Included_ru_funnydwarf_iot_nml_JNILibrary
#define _Included_ru_funnydwarf_iot_nml_JNILibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_funnydwarf_iot_nml_JNILibrary
 * Method:    wiringPiSetup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_funnydwarf_iot_nml_JNILibrary_wiringPiSetup
        (JNIEnv *env, jclass js);

#ifdef __cplusplus
}
#endif
#endif
