/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_funnydwarf_iot_nml_PinDigitalReader */

#ifndef _Included_ru_funnydwarf_iot_nml_PinDigitalReader
#define _Included_ru_funnydwarf_iot_nml_PinDigitalReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_funnydwarf_iot_nml_PinDigitalReader
 * Method:    digitalRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_funnydwarf_iot_nml_PinDigitalReader_digitalRead
  (JNIEnv *env, jclass jc, jint pin);

#ifdef __cplusplus
}
#endif
#endif
