/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_funnydwarf_iot_nml_modules_onewire_OneWire */

#ifndef _Included_ru_funnydwarf_iot_nml_modules_onewire_OneWire
#define _Included_ru_funnydwarf_iot_nml_modules_onewire_OneWire
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_funnydwarf_iot_nml_modules_onewire_OneWire
 * Method:    searchDevices
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_ru_funnydwarf_iot_nml_modules_onewire_OneWire_searchDevices
  (JNIEnv *env, jclass jc, jint pornNumber);

#ifdef __cplusplus
}
#endif
#endif
